# general settings
name: Ours_GAN
model_type: ESRGANModel_V2
scale: 5 # 5배 업스케일링
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: CustomDataset
    type: NumpyPairedDataset # 사용자 정의 데이터셋 클래스 이름
    dataroot_gt: /home/wj/works/Wind_Speed_Data/processed2/train/HR.npy # HR 데이터 경로
    dataroot_lq: /home/wj/works/Wind_Speed_Data/processed2/train/LR.npy # LR 데이터 경로
    filename_tmpl: '{}'
    io_backend:
      type: numpy # numpy 배열을 사용
    gt_size: 100 # HR 데이터 크기
    use_hflip: false # 데이터 증강: 수평 뒤집기
    use_rot: false # 데이터 증강: 회전
    # data loader
    num_worker_per_gpu: 8  # ✅ 성능 최적화
    batch_size_per_gpu: 32  # ✅ 메모리 안정성을 고려하여 32 → 24로 조정
    dataset_enlarge_ratio: 1 #데이터 증강 없이 그대로 사용
    prefetch_mode: ~

  val:
    name: CustomValDataset
    type: NumpyPairedDataset # 검증 데이터셋도 같은 구조 사용
    dataroot_gt: /home/wj/works/Wind_Speed_Data/processed2/val/HR.npy
    dataroot_lq: /home/wj/works/Wind_Speed_Data/processed2/val/LR.npy
    io_backend:
      type: numpy

network_g:
  type: FASR_CNN_Hybrid
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 64
  num_group: 6
 #num_block: 6
  img_range: 1.0
  rgb_mean: [0.0]        # 1채널이므로 단일값
  # 주석처리된 업스케일, 필요시 해제
  upscale: 5


network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 1 # Discriminator도 1채널 데이터 입력
  num_feat: 64


# path
path:
  experiments_root: experiments/paper  # 명시적으로 지정한 experiments_root
  pretrain_network_g: ~ # 사전 학습된 모델이 없는 경우
  strict_load_g: true
  resume_state: ~ # 학습 상태를 처음부터 시작

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [60000, 75000, 84000]  # 69%, 86%, 96%
    gamma: 0.7

  total_iter: 87500
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1.0      # ↓ 약간 줄임

  #patch_opt:
  #  type: GradientLoss
  #  loss_weight: !!float 0.1     # ↑ edge 보존 강화

  #wavelet_opt:
  #  type: WaveletHighFrequencyLoss
  #  loss_weight: !!float 0.05    # ↑ 더 많은 텍스처 유도

  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 0.01    # 약간 강화 (더 디테일 유도)

  net_d_iters: 1 # 잠시 1에서 0으로 변경
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 3.5e3  # 1 epoch마다 검증
  save_img: true

  metrics:
    rmse: # metric name, can be arbitrary
      type: calculate_rmse
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 3.5e3  # 1 epoch마다 검증
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
