# TODO
# general settings
name: HAN_for_wind_speed
model_type: SRModel
scale: 5
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: CustomDataset
    type: NumpyPairedDataset
    dataroot_gt: /home/wj/works/Wind_Speed_Data/processed2/train/HR.npy
    dataroot_lq: /home/wj/works/Wind_Speed_Data/processed2/train/LR.npy
    filename_tmpl: '{}'
    io_backend:
      type: numpy

    gt_size: 100
    use_hflip: false
    use_rot: false

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: CustomValDataset
    type: NumpyPairedDataset
    dataroot_gt: /home/wj/works/Wind_Speed_Data/processed2/val/HR.npy
    dataroot_lq: /home/wj/works/Wind_Speed_Data/processed2/val/LR.npy
    io_backend:
      type: numpy

# network structures
network_g:
  type: HAN
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 64
  num_group: 10
  num_block: 20
  reduction: 16
  upscale: 5
  img_range: 1.0
  rgb_mean: [0.0]


# path
path:
  experiments_root: experiments/paper  # 명시적으로 지정한 experiments_root
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [60000, 75000, 84000]  # 69%, 86%, 96%
    gamma: 0.7

  total_iter: 87500
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 3.5e3  # 1 epoch마다 검증
  save_img: true

  metrics:
    rmse: # metric name, can be arbitrary
      type: calculate_rmse
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 3.5e3  # 1 epoch마다 검증
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
