# general settings
name: HAT_korea
model_type: HATModel
scale: 5
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: KoreaTrainDataset
    type: NumpyPairedKorea # 사용자 정의 데이터셋 클래스 이름
    dataroot_gt: /home/wj/works/Wind_Speed_Data/Korea/train/HR_2012to2020.npy # HR 데이터 경로
    dataroot_lq: /home/wj/works/Wind_Speed_Data/Korea/train/LR_2012to2020.npy # LR 데이터 경로
    filename_tmpl: '{}'
    io_backend:
      type: numpy

    gt_size: 100
    use_hflip: false
    use_rot: false

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32 # 배치사이즈 4
    dataset_enlarge_ratio: 1 # 데이터 증강 X
    prefetch_mode: ~

  val:
    name: KoreaValDataset
    type: NumpyPairedKorea # 검증 데이터셋도 같은 구조 사용
    dataroot_gt: /home/wj/works/Wind_Speed_Data/Korea/val/HR_2021to2022.npy
    dataroot_lq: /home/wj/works/Wind_Speed_Data/Korea/val/LR_2021to2022.npy
    io_backend:
      type: numpy

# network structures
network_g:
  type: HAT
  upscale: 5             # 4 → 5 (데이터와 일치)
  in_chans: 1            # 3 → 1 (풍속 1채널)
  img_size: 20           # 입력 이미지 크기 (20x20)
  window_size: 5         # 20/5 = 4 → window 완전 분할 가능
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.          # 풍속 정규화 기준
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 96
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'


# path
path:
  experiments_root: experiments/korea # 명시적으로 지정한 experiments_root
  pretrain_network_g: ~ # 사전 학습된 모델이 없는 경우
  strict_load_g: true
  resume_state: ~ # 학습 상태를 처음부터 시작

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [60000, 75000, 84000]  # 69%, 86%, 96%
    gamma: 0.7

  total_iter: 87500 # 100에포크
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 505  # 1 epoch마다 검증
  save_img: true

  metrics:
    rmse: # metric name, can be arbitrary
      type: calculate_rmse
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 505  # 1 epoch마다 검증
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
